version: "3.8"

services:
  backend:
    build: ../comparathor-backend  # Path to backend repo
    container_name: comparathor-backend
    restart: always
    environment:
      DATABASE_URL: "mysql://user:password@mysql:3306/mydb"
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ../comparathor-frontend  # Path to frontend repo
    container_name: comparathor-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
  monitoring:

volumes:
  grafana_data:
