version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 10s

  backend:
    build: ../comparathor-backend
    container_name: comparathor-backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ../comparathor-backend/.env  # Load backend .env file
    environment:
      DB_URL: "mysql://user:password@mysql:3306/mydb"  # Override development DB
      CORS_ORIGINS: "http://localhost,http://localhost:80"
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    build: ../comparathor-frontend
    container_name: comparathor-frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ../comparathor-frontend/.env  # Load frontend .env file
    environment:
      VITE_API_BASE_URL: "http://backend:8000/api"  # Adjust for Docker network
    ports:
      - "4173:4173"
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring
      - app_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - monitoring

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
  monitoring:

volumes:
  mysql_data:
  grafana_data:
